language: c
env:
    - PG=9.4
    - PG=9.3
    - PG=9.2
install:
    - sudo /etc/init.d/postgresql stop
    - sudo apt-get update -o Dir::Etc::sourcelist=/dev/null
    - sudo apt-get install postgresql-$PG postgresql-server-dev-$PG
    - sudo /etc/init.d/postgresql start $PG
script:
    - psql postgres -xA -c 'select version()'
    - make
    - sudo make install
    - make installcheck || (cat regression.diffs && false)
